version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - misspell
    - unused
    - ineffassign
    - gocritic
  exclusions:
    rules:
      - linters: [misspell]
        path: _test\.go

  settings:
    gocritic:
      enabled-checks:
        - dupImport
        - nestingReduce
        - truncateCmp
        - unnamedResult

formatters:
  enable:
    - gofmt
    - goimports

output:
  sort-order:
    - file
