version: 2
before:
  hooks:
    - go mod download
builds:
  - id: kubectl-schemagen
    main: ./cmd/kubectl-schemagen
    binary: kubectl-schemagen
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - builds:
      - kubectl-schemagen
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    format: tar.gz
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
